'use strict';
const $=id=>document.getElementById(id),S=RaceSim,canvas=$('game'),ctx=canvas.getContext('2d');
const keys=new Set(),W=1200,H=760;let g,t,mode='menu',myId='you',session=null,pollTimer=null,networkBusy=false,queuedItem=false,paused=false,last=0,camera=null,world=[],visuals=new Map(),sound=false,audio,resultShown=false,failures=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),angleDiff=(a,b)=>Math.atan2(Math.sin(a-b),Math.cos(a-b));

const itemArtwork={
Boost:'<path d="M36 7C21 17 17 30 21 43l12 3C47 36 51 22 49 7Z" fill="#ffcc61" stroke="#fff1c1" stroke-width="3"/><circle cx="36" cy="23" r="6" fill="#5ccddd"/><path d="m19 36-10 8 10 2m17-2-3 12 11-9" fill="#ee8467"/><path d="m23 48-7 12 12-7" fill="#fff4b5"/>',
Shield:'<path d="M32 7 53 16v16c0 12-11 21-21 27C22 53 11 44 11 32V16Z" fill="#65d7f4" stroke="#dcffff" stroke-width="3"/><path d="M32 16v31C43 40 45 33 45 22Z" fill="#2697cc"/><path d="m23 31 6 6 13-13" fill="none" stroke="white" stroke-width="4"/>',
Pulse:'<circle cx="32" cy="32" r="23" fill="#ad87ec" stroke="#dfc9ff" stroke-width="3"/><path d="m34 12-17 24h13l-2 17 20-27H34Z" fill="#fff3bd"/><path d="M5 15 1 9m58 39 4 7M6 49l-5 6m56-40 6-7" stroke="#dfb5ff" stroke-width="3"/>',
Empty:'<path d="M22 21c0-14 24-14 24 0 0 8-14 9-14 19" fill="none" stroke="#8598b1" stroke-width="6" stroke-linecap="round"/><circle cx="32" cy="51" r="4" fill="#8598b1"/>'};
const itemDescriptions={Boost:'A burst of extra speed',Shield:'Blocks hits for 6 seconds',Pulse:'Slows a rival ahead',Empty:'Drive through a ? box'};
const itemCard=document.createElement('button');itemCard.id='powerCard';itemCard.className='power-card';itemCard.setAttribute('aria-label','No power-up held');itemCard.innerHTML='<span class="power-heading">YOUR POWER-UP</span><span id="powerArt"></span><strong id="powerName">EMPTY SLOT</strong><span id="powerHint">Drive through a ? box</span><span class="power-key">SPACE / TAP TO USE</span>';document.querySelector('.stage').appendChild(itemCard);itemCard.onclick=()=>{queuedItem=true;itemCard.blur();};let previousItem='',lastResultUpdate=0;
function powerHud(p){const held=p.item||'Empty',active=p.shield>0?'Shield':p.boost>0?'Boost':p.stun>0?'Pulse':null,shown=held==='Empty'&&active?active:held,key=shown+'|'+held+'|'+active;
itemCard.hidden=mode==='menu'||g.phase==='lobby'||!$('results').hidden;itemCard.disabled=!p.item;itemCard.classList.toggle('ready',!!p.item);itemCard.classList.toggle('active',held==='Empty'&&!!active);
if(key!==previousItem){$('powerArt').innerHTML='<svg viewBox="0 0 64 64" aria-hidden="true">'+itemArtwork[shown]+'</svg>';$('powerName').textContent=held==='Empty'&&active?active.toUpperCase()+' ACTIVE':held==='Empty'?'EMPTY SLOT':held.toUpperCase();$('powerHint').textContent=itemDescriptions[shown];itemCard.setAttribute('aria-label',p.item?'Use '+p.item+' power-up':active?active+' active':'No power-up. Drive through a question-mark box.');if(p.item&&previousItem)beep();previousItem=key;}
}
function format(n){return Math.floor(n/60)+':'+(n%60).toFixed(1).padStart(4,'0');}
function me(){return g.racers.find(r=>r.id===myId)||g.racers[0];}
function beep(){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),v=audio.createGain();o.frequency.value=650;v.gain.setValueAtTime(.035,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.15);o.connect(v);v.connect(audio.destination);o.start();o.stop(audio.currentTime+.15);}catch{}}
function input(){return{gas:keys.has('w')||keys.has('arrowup'),brake:keys.has('s')||keys.has('arrowdown'),steer:(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),drift:keys.has('shift'),item:queuedItem};}
function preview(){t=S.circuit(+$('track').value);g=S.create(+$('track').value,+$('difficulty').value);g.racers=[S.racer(t,'you','You',0)];g.racers[0].color=$('color').value;camera=null;visuals.clear();makeWorld();}
function solo(){session=null;myId='you';preview();for(let i=1;i<6;i++)g.racers.push(S.racer(t,'bot'+i,['You','Pip','Nova','Mango','Violet','Ghost'][i],i,true));S.start(g,t);mode='solo';paused=false;resultShown=false;hidePanels();keys.clear();$('start').blur();}
function hidePanels(){for(const id of ['menu','paused','results','lobby'])$(id).hidden=true;}
function returnMenu(){if(session){const old=session;fetch('/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...old,action:'leave'}),keepalive:true}).catch(()=>{});}session=null;clearTimeout(pollTimer);mode='menu';myId='you';$('connection').textContent='3D · CHROMEBOOK FRIENDLY';paused=false;keys.clear();hidePanels();$('menu').hidden=false;$('toast').textContent='';preview();}
async function api(action,extra={}){const res=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...session,action,...extra}),signal:AbortSignal.timeout(10000)});let data;try{data=await res.json();}catch{throw new Error('Multiplayer needs the online game server. Use the multiplayer site link.');}if(!res.ok)throw new Error(data.error||'Connection failed');return data;}
function lobbyUI(data){$('roomCode').textContent=data.code;$('players').replaceChildren(...data.game.racers.filter(r=>!r.bot).map(r=>{const li=document.createElement('li');li.textContent=r.name+(r.id===data.host?' · host':'');return li;}));$('hostStart').hidden=data.host!==myId;$('lobbyHint').textContent=data.host===myId?'Share this code, wait for friends, then start. Empty spots get AI racers.':'Waiting for the host to start…';}
async function connect(action){if(networkBusy)return;networkBusy=true;$('netStatus').textContent='Connecting…';try{const data=await api(action,{name:$('nickname').value,code:$('joinCode').value.trim().toUpperCase(),track:+$('track').value});session={id:data.id,token:data.token,code:data.code};myId=data.id;g=data.game;t=S.circuit(g.track);makeWorld();camera=null;visuals.clear();mode='online';failures=0;resultShown=false;hidePanels();$('lobby').hidden=false;lobbyUI(data);$('netStatus').textContent='';sync();}catch(e){$('netStatus').textContent=e.message;}finally{networkBusy=false;}}
async function sync(){if(!session)return;const active=session;try{const sent=input();queuedItem=false;const data=await api('sync',{input:sent});if(session!==active)return;g=data.game;failures=0;$('connection').textContent='ONLINE · '+session.code;if(g.phase==='lobby')lobbyUI(data);else $('lobby').hidden=true;}catch(e){if(session!==active)return;failures++;$('connection').textContent='CONNECTION LOST · retrying';if(failures>=4){returnMenu();$('netStatus').textContent='Disconnected: '+e.message;return;}}if(session===active)pollTimer=setTimeout(sync,g.phase==='lobby'?450:65);}
async function hostStart(){try{const data=await api('start');g=data.game;$('lobby').hidden=true;keys.clear();$('hostStart').blur();}catch(e){$('lobbyHint').textContent=e.message;}}
function pause(){if(mode==='menu')return;if(mode==='online'){$('toast').textContent='Online races keep running. Hold brake to stop.';return;}paused=!paused;$('paused').hidden=!paused;keys.clear();}
function result(){resultShown=true;const p=me(),order=S.order(g),place=order.indexOf(p)+1;$('resultTitle').textContent=p.finish===null?'Race ended':place===1?'You take the gold!':'Finished '+place+(['st','nd','rd'][place-1]||'th')+'!';$('resultTime').textContent=t.name+' · '+format(p.finish??g.elapsed)+' · penalties +'+p.penalty+'s'+(g.phase!=='finished'?' · provisional until all racers finish':'');if(mode==='solo'&&p.finish!==null){try{const k='turbo-trails-3d-best-'+g.track+'-'+g.difficulty,old=+localStorage.getItem(k);if(!old||p.finish<old)localStorage.setItem(k,p.finish);}catch{}};$('standings').replaceChildren(...order.map(r=>{const li=document.createElement('li');li.textContent=r.name+' — '+(r.finish===null?'racing…':format(r.finish))+' (+'+r.penalty+'s)';return li;}));$('results').hidden=false;$('again').hidden=mode==='online';keys.clear();}
function hud(){const p=me();if(!p)return;$('position').textContent=(S.order(g).findIndex(r=>r.id===myId)+1)+' / '+g.racers.length;$('lap').textContent=clamp(Math.floor(p.total/t.length)+1,1,3)+' / 3';$('time').textContent=format(g.elapsed+p.penalty);$('speed').textContent=Math.round(p.speed*.7);$('item').textContent=p.item||'—';powerHud(p);$('drift').style.width=(p.drift/1.3*100)+'%';$('penalty').textContent='PENALTIES +'+p.penalty+'s';if(mode==='menu')return;let msg='';if(g.phase==='countdown')msg=String(Math.max(1,Math.ceil(g.countdown)));else if(p.resetNotice>0)msg='TRACK RESET · +3 SECONDS';else if(p.offTime>0)msg='OFF TRACK · SLOWDOWN · RETURN NOW';else if(p.drift>=1)msg='RELEASE DRIFT FOR BOOST';else if(p.boost>0)msg='TURBO BOOST';else if(p.shield>0)msg='SHIELD ACTIVE';$('toast').textContent=msg;if((p.finish!==null||g.phase==='finished')&&performance.now()-lastResultUpdate>500){lastResultUpdate=performance.now();result();}}
// Perspective 3D renderer: world-space polygons, near-plane clipping, depth sorting.
function poly(points,color,text=''){return{points,color,text};}
function box(x,z,y,w,d,h,color,angle=0){const c=Math.cos(angle),s=Math.sin(angle),v=(a,b,k)=>({x:x+a*c-b*s,z:z+a*s+b*c,y:y+k}),p=[v(-w/2,-d/2,0),v(w/2,-d/2,0),v(w/2,d/2,0),v(-w/2,d/2,0)],q=[v(-w/2,-d/2,h),v(w/2,-d/2,h),v(w/2,d/2,h),v(-w/2,d/2,h)];return[poly(q,color),...p.map((a,i)=>poly([a,p[(i+1)%4],q[(i+1)%4],q[i]],i%2?shade(color,.7):shade(color,.85)))];}
function shade(hex,f){return '#'+[1,3,5].map(i=>Math.round(parseInt(hex.slice(i,i+2),16)*f).toString(16).padStart(2,'0')).join('');}
function point(s,lane,y=0){const p=S.sample(t,s,lane);return{x:p.x,z:p.y,y};}

function ringShape(x,z,y,radius,height,color,sides=8){const faces=[];for(let i=0;i<sides;i++){const a=i*Math.PI*2/sides,b=(i+1)*Math.PI*2/sides;faces.push(poly([{x:x+Math.cos(a)*radius,z:z+Math.sin(a)*radius,y},{x:x+Math.cos(b)*radius,z:z+Math.sin(b)*radius,y},{x,z,y:y+height}],shade(color,.72+.28*(i%3)/2)));}return faces;}
function makeWorld(){
world=[];
// Broad, quiet ground bands give depth without texture downloads.
for(let i=0;i<13;i++)world.push(poly([{x:-800,z:i*100,y:-.3},{x:2000,z:i*100,y:-.3},{x:2000,z:i*100+100,y:-.3},{x:-800,z:i*100+100,y:-.3}],i%2?t.ground:shade(t.ground,.95)));
if(g.track===0){world.push(poly([{x:-900,z:-900,y:-1},{x:2000,z:-900,y:-1},{x:2000,z:-85,y:-1},{x:-900,z:-85,y:-1}],'#3eaec9'));for(let i=0;i<10;i++)world.push(poly([{x:-800,z:-90-i*35,y:0},{x:1900,z:-90-i*35,y:0},{x:1900,z:-92-i*35,y:0},{x:-800,z:-92-i*35,y:0}],'#8adadd'));}
for(let i=0;i<t.path.length;i++){const a=t.path[i],end=a.s+a.len;
world.push(poly([point(a.s,-64),point(end,-64),point(end,64),point(a.s,64)],g.track===1?'#d2ae86':'#acc78a'));
world.push(poly([point(a.s,-53,.12),point(end,-53,.12),point(end,53,.12),point(a.s,53,.12)],i%3?'#f6f0d9':'#ed675e'));
world.push(poly([point(a.s,-47,.35),point(end,-47,.35),point(end,47,.35),point(a.s,47,.35)],g.track===2?'#38415b':'#444e57'));
for(const side of [-1,1])world.push(poly([point(a.s,side*44,.52),point(end,side*44,.52),point(end,side*45,.52),point(a.s,side*45,.52)],'#e8e5da'));
// Tire marks follow the racing line through bends.
if(i%3!==0)for(const lane of [-15,15])world.push(poly([point(a.s,lane,.55),point(end,lane,.55),point(end,lane+1.1,.55),point(a.s,lane+1.1,.55)],'#343e47'));
if(i%3===0)for(const side of [-1,1]){const p=point(a.s,side*69);world.push(...box(p.x,p.z,0,3,3,10,'#d7dce1'));}
if(i%3===0){const b=t.path[(i+3)%t.path.length];for(const side of [-1,1])world.push(poly([point(a.s,side*69,6),point(b.s,side*69,6),point(b.s,side*69,10),point(a.s,side*69,10)],g.track===2?'#8999dd':'#d2dce0'));}
}
for(let i=0;i<12;i++)for(let j=0;j<2;j++)world.push(poly([point(j*6,i*8-48,.7),point(j*6+6,i*8-48,.7),point(j*6+6,i*8-40,.7),point(j*6,i*8-40,.7)],(i+j)%2?'#fffbea':'#1c2734'));
for(let i=0;i<6;i++){const s=-25-i*25,lane=(i%2?1:-1)*17;world.push(poly([point(s-10,lane-12,.8),point(s-8,lane-12,.8),point(s-8,lane+12,.8),point(s-10,lane+12,.8)],'#dadcce'));}
for(const f of [.25,.68]){const s=t.length*f;world.push(poly([point(s-17,-32,1),point(s+17,-32,1),point(s+17,32,1),point(s-17,32,1)],'#f6bf56'));for(let k=0;k<3;k++)world.push(poly([point(s-12+k*10,-20,1.1),point(s-4+k*10,0,1.1),point(s-12+k*10,20,1.1)],'#fff5cf'));}
// Start gantry and branded circuit boards.
for(const side of [-1,1]){const p=point(20,side*62);world.push(...box(p.x,p.z,0,5,5,67,'#e0e5e6'));}
world.push(poly([point(20,-65,55),point(20,65,55),point(20,65,72),point(20,-65,72)],'#173047','TURBO TRAILS'));
for(const f of [.2,.46,.73]){const s=t.length*f;world.push(poly([point(s-26,-83,10),point(s+26,-83,10),point(s+26,-83,30),point(s-26,-83,30)],g.track===2?'#634ba8':'#257c73','GO!  GO!'));
const p=point(s,90);world.push(...box(p.x,p.z,0,8,8,5,'#eeeece'));world.push(...ringShape(p.x,p.z,5,5,14,'#f29550',6));}
for(let i=0;i<85;i++){const x=(i*173+47)%1400-100,z=(i*137+29)%960-70;if(S.nearest(t,x,z).distance<100)continue;
if(g.track===0){world.push(...box(x,z,0,4,4,43,'#b48b5e'));for(let j=0;j<6;j++){const a=j*Math.PI/3,dx=Math.cos(a),dz=Math.sin(a);world.push(poly([{x:x-dz*4,z:z+dx*4,y:43},{x:x+dx*14,z:z+dz*14,y:49},{x:x+dx*32,z:z+dz*32,y:36},{x:x+dz*4,z:z-dx*4,y:43}],j%2?'#438e59':'#63ae6a'));}}
else if(g.track===1){world.push(...ringShape(x,z,0,14+i%22,20+i%45,'#b8886b',6));if(i%3===0)world.push(...box(x+20,z,0,6,6,34,'#668867'));}
else{world.push(...box(x,z,0,4,4,20,'#5d637d'));world.push(...ringShape(x,z,12,20,48,'#3f7272'));if(i%4===0){world.push(...box(x+22,z,0,2,2,58,'#677797'));world.push(...box(x+22,z,58,12,6,3,'#f7e9b2'));}}
}
}
function kart(r){
const c=Math.cos(r.angle),s=Math.sin(r.angle),v=(x,z,y)=>({x:r.x+x*c-z*s,z:r.y+x*s+z*c,y});const list=[];
const addBox=(x,z,y,w,d,h,col)=>{const p=v(x,z,y);list.push(...box(p.x,p.z,p.y,w,d,h,col,r.angle));};
// Sculpted lower chassis and tapered nose, rather than a single rectangular body.
const outline=[[-17,-8],[-10,-11],[8,-10],[20,-6],[22,0],[20,6],[8,10],[-10,11],[-17,8]];
const low=outline.map(([x,z])=>v(x,z,5)),top=outline.map(([x,z])=>v(x*.94,z*.85,11));list.push(poly(top,r.color));for(let i=0;i<low.length;i++)list.push(poly([low[i],low[(i+1)%low.length],top[(i+1)%low.length],top[i]],shade(r.color,i%2?.72:.9)));
addBox(8,0,11,16,3,.5,'#fff3d5');addBox(-5,0,10,15,13,3,'#243442');addBox(-11,0,13,3,12,8,'#263844');
// Round tires with sidewalls, metallic hubs and radial highlights.
for(const x of [-11,12])for(const z of [-12,12]){const a=[],b=[];for(let i=0;i<10;i++){const angle=i*Math.PI/5; a.push(v(x+Math.cos(angle)*6,z-3,6+Math.sin(angle)*6));b.push(v(x+Math.cos(angle)*6,z+3,6+Math.sin(angle)*6));}list.push(poly(a,'#172333'),poly(b,'#172333'));for(let i=0;i<10;i++)list.push(poly([a[i],a[(i+1)%10],b[(i+1)%10],b[i]],i%2?'#283241':'#202a37'));for(const side of [-1,1]){const hub=[];for(let i=0;i<8;i++)hub.push(v(x+Math.cos(i*Math.PI/4)*3,z+side*3.15,6+Math.sin(i*Math.PI/4)*3));list.push(poly(hub,'#b6c7d5'));}}
addBox(-17,-7,13,2,2,8,'#657786');addBox(-17,7,13,2,2,8,'#657786');addBox(-18,0,21,5,29,2,r.color);addBox(-21,0,23,1,27,.7,'#fff2cf');
// Driver suit, gloves, faceted rounded helmet and dark visor.
addBox(-5,0,13,8,9,9,r.color);addBox(3,-5,16,7,3,3,'#fff0d7');addBox(3,5,16,7,3,3,'#fff0d7');addBox(7,0,16,2,11,2,'#25303a');
const rings=[];for(let j=0;j<5;j++){const theta=j*Math.PI/4,rr=Math.sin(theta)*7;const row=[];for(let i=0;i<10;i++)row.push(v(-5+Math.cos(i*Math.PI/5)*rr,Math.sin(i*Math.PI/5)*rr,29+Math.cos(theta)*7));rings.push(row);}for(let j=0;j<4;j++)for(let i=0;i<10;i++)list.push(poly([rings[j][i],rings[j][(i+1)%10],rings[j+1][(i+1)%10],rings[j+1][i]],j===1&&(i<2||i>7)?'#20364b':j===0?'#fff9e7':shade('#f4f2df',.83+j*.035)));
addBox(19,-5,9,2,3,2,'#fff8ce');addBox(19,5,9,2,3,2,'#fff8ce');addBox(-18,-6,9,1,3,2,'#ff786e');addBox(-18,6,9,1,3,2,'#ff786e');
for(const z of [-7,7]){addBox(-19,z,5,4,3,3,'#899aaa');if(r.boost>0)list.push(poly([v(-21,z-2,5),v(-21,z+2,5),v(-38-Math.random()*12,z,7)],'#ffce64'));if(r.drift>.2){list.push(poly([v(-13,z*1.8,3),v(-22-Math.random()*8,z*2,2),v(-17,z*2.2,5)],r.drift>=1?'#ffcd6b':'#65e4ff'));}}
// Ground contact shadow and orbiting shield.
const shadow=[];for(let i=0;i<12;i++)shadow.push(v(Math.cos(i*Math.PI/6)*25,Math.sin(i*Math.PI/6)*18,.8));list.push(poly(shadow,'#253e3c'));
if(r.shield>0)for(let i=0;i<16;i++){const a=i*Math.PI/8,b=(i+1)*Math.PI/8;list.push(poly([v(Math.cos(a)*29,Math.sin(a)*29,5),v(Math.cos(b)*29,Math.sin(b)*29,5),v(Math.cos(b)*29,Math.sin(b)*29,7),v(Math.cos(a)*29,Math.sin(a)*29,7)],'#86f4ff'));}
return list;
}
function draw(dt){let p=me();if(!p)return;const alpha=1-Math.exp(-dt*18);for(const r of g.racers){let v=visuals.get(r.id);if(!v||Math.hypot(v.x-r.x,v.y-r.y)>120){v={...r};visuals.set(r.id,v);}else{v.x+=(r.x-v.x)*alpha;v.y+=(r.y-v.y)*alpha;v.angle+=angleDiff(r.angle,v.angle)*alpha;for(const k of ['boost','shield','color','name','drift'])v[k]=r[k];}}p=visuals.get(p.id)||p;
const target={x:p.x-Math.cos(p.angle)*112,z:p.y-Math.sin(p.angle)*112,y:64,angle:p.angle};if(!camera)camera=target;else{const f=1-Math.exp(-dt*7);camera.x+=(target.x-camera.x)*f;camera.z+=(target.z-camera.z)*f;camera.angle+=angleDiff(target.angle,camera.angle)*f;}
const ca=Math.cos(camera.angle),sa=Math.sin(camera.angle),pitch=.29,cp=Math.cos(pitch),sp=Math.sin(pitch),focal=680;
function view(v){const dx=v.x-camera.x,dz=v.z-camera.z,forward=dx*ca+dz*sa,h=v.y-camera.y;return{x:-dx*sa+dz*ca,y:h*cp+forward*sp,z:forward*cp-h*sp};}
function project(v){return{x:W/2+v.x*focal/v.z,y:H*.43-v.y*focal/v.z};}
const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,t.sky);sky.addColorStop(.55,g.track===2?'#47627b':'#f2edcf');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle=t.ground;ctx.fillRect(0,H*.43-Math.tan(pitch)*focal,W,H);
const horizon=H*.43-Math.tan(pitch)*focal;
for(let layer=0;layer<2;layer++){ctx.fillStyle=g.track===2?(layer?'#394d67':'#596781'):g.track===1?(layer?'#a07c73':'#c89f8e'):(layer?'#7daca4':'#accbc3');ctx.beginPath();ctx.moveTo(0,horizon+18);for(let i=0;i<=24;i++)ctx.lineTo(i*55,horizon-10-Math.sin(i*.7+layer*2)*22-(layer?10:30));ctx.lineTo(W,horizon+18);ctx.fill();}
ctx.fillStyle=g.track===2?'#fff5cf':'#fff3cb';ctx.beginPath();ctx.arc(950,62,g.track===2?17:26,0,Math.PI*2);ctx.fill();
let scene=world.slice();for(const r of g.racers)scene.push(...kart(visuals.get(r.id)||r));for(let i=0;i<4;i++)if(!g.boxes[i]){const b=S.sample(t,t.length*[.15,.36,.58,.8][i]);const itemFaces=box(b.x,b.y,12+Math.sin(performance.now()/400)*3,19,19,19,['#af8ff0','#6ccfee','#efba71','#81dcb0'][i],performance.now()/1100);for(const face of itemFaces)face.text='?';scene.push(...itemFaces);}
const faces=[];for(const face of scene){let vertices=face.points.map(view);if(vertices.every(v=>v.z<5)||vertices.every(v=>v.z>1500))continue;let clipped=[];for(let i=0;i<vertices.length;i++){const a=vertices[i],b=vertices[(i+1)%vertices.length];if(a.z>=5)clipped.push(a);if((a.z>=5)!==(b.z>=5)){const f=(5-a.z)/(b.z-a.z);clipped.push({x:a.x+(b.x-a.x)*f,y:a.y+(b.y-a.y)*f,z:5});}}if(clipped.length<3)continue;const points=clipped.map(project);if(points.every(p=>p.x<0)||points.every(p=>p.x>W)||points.every(p=>p.y<0)||points.every(p=>p.y>H))continue;faces.push({points,color:face.color,text:face.text,depth:(face.points.every(p=>p.y<0)?1000000:0)+vertices.reduce((a,v)=>a+v.z,0)/vertices.length});}faces.sort((a,b)=>b.depth-a.depth);for(const f of faces){ctx.fillStyle=f.color;ctx.beginPath();f.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fill();ctx.strokeStyle=f.color;ctx.lineWidth=.5;ctx.stroke();if(f.text){const xs=f.points.map(p=>p.x),ys=f.points.map(p=>p.y),width=Math.max(...xs)-Math.min(...xs),height=Math.max(...ys)-Math.min(...ys);if(width>30){ctx.fillStyle='#fff7d8';ctx.textAlign='center';ctx.font='900 '+Math.min(28,height*.48,width/f.text.length*1.25)+'px system-ui';ctx.fillText(f.text,(Math.min(...xs)+Math.max(...xs))/2,(Math.min(...ys)+Math.max(...ys))/2+height*.16);}}}
// Mini-map remains readable while the chase camera follows the kart.
ctx.fillStyle='#132239dd';ctx.fillRect(20,H-155,190,135);ctx.strokeStyle='#8096ac';ctx.lineWidth=5;ctx.beginPath();t.path.forEach((p,i)=>{const x=30+p.x*.14,y=H-145+p.y*.14;i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.closePath();ctx.stroke();for(const r of g.racers){ctx.fillStyle=r.id===myId?'#b9ff66':r.color;ctx.beginPath();ctx.arc(30+r.x*.14,H-145+r.y*.14,r.id===myId?5:3,0,Math.PI*2);ctx.fill();}
}
function frame(now){const dt=Math.min((now-last)/1000||.016,.04);last=now;if(mode==='solo'&&!paused){const p=me();p.input=input();queuedItem=false;S.step(g,t,dt);}draw(dt);hud();requestAnimationFrame(frame);}
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','BUTTON'].includes(document.activeElement.tagName))return;const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();keys.add(k);if(!e.repeat){if(k===' ')queuedItem=true;if(k==='p'||k==='escape')pause();}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();if(mode==='solo'&&!paused)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();if(mode==='solo'&&!paused)pause();}});
for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);});for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>keys.delete(b.dataset.key));}
$('start').onclick=solo;$('again').onclick=()=>{solo();$('again').blur();};$('pause').onclick=()=>{pause();$('pause').blur();};$('resume').onclick=()=>{pause();$('resume').blur();};$('quit').onclick=returnMenu;$('change').onclick=returnMenu;$('leave').onclick=returnMenu;$('track').onchange=preview;$('color').onchange=preview;$('touchItem').onclick=()=>{queuedItem=true;$('touchItem').blur();};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(sound));beep();$('sound').blur();};$('createRoom').onclick=()=>connect('create');$('joinRoom').onclick=()=>connect('join');$('hostStart').onclick=hostStart;
$('copyCode').onclick=async()=>{try{await navigator.clipboard.writeText(session.code);$('lobbyHint').textContent='Room code copied!';}catch{$('lobbyHint').textContent='Share the room code shown above.';}};
preview();requestAnimationFrame(frame);
