'use strict';
const $=id=>document.getElementById(id),S=RaceSim,canvas=$('game'),ctx=canvas.getContext('2d');
const keys=new Set(),W=1200,H=760;let g,t,mode='menu',myId='you',session=null,pollTimer=null,networkBusy=false,queuedItem=false,paused=false,last=0,camera=null,world=[],visuals=new Map(),sound=false,audio,resultShown=false,failures=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),angleDiff=(a,b)=>Math.atan2(Math.sin(a-b),Math.cos(a-b));
function format(n){return Math.floor(n/60)+':'+(n%60).toFixed(1).padStart(4,'0');}
function me(){return g.racers.find(r=>r.id===myId)||g.racers[0];}
function beep(){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),v=audio.createGain();o.frequency.value=650;v.gain.setValueAtTime(.035,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.15);o.connect(v);v.connect(audio.destination);o.start();o.stop(audio.currentTime+.15);}catch{}}
function input(){return{gas:keys.has('w')||keys.has('arrowup'),brake:keys.has('s')||keys.has('arrowdown'),steer:(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),drift:keys.has('shift'),item:queuedItem};}
function preview(){t=S.circuit(+$('track').value);g=S.create(+$('track').value,+$('difficulty').value);g.racers=[S.racer(t,'you','You',0)];g.racers[0].color=$('color').value;camera=null;visuals.clear();makeWorld();}
function solo(){session=null;myId='you';preview();for(let i=1;i<6;i++)g.racers.push(S.racer(t,'bot'+i,['You','Pip','Nova','Mango','Violet','Ghost'][i],i,true));S.start(g,t);mode='solo';paused=false;resultShown=false;hidePanels();keys.clear();$('start').blur();}
function hidePanels(){for(const id of ['menu','paused','results','lobby'])$(id).hidden=true;}
function returnMenu(){if(session){const old=session;fetch('/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...old,action:'leave'}),keepalive:true}).catch(()=>{});}session=null;clearTimeout(pollTimer);mode='menu';paused=false;keys.clear();hidePanels();$('menu').hidden=false;$('toast').textContent='';preview();}
async function api(action,extra={}){const res=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...session,action,...extra}),signal:AbortSignal.timeout(10000)});let data;try{data=await res.json();}catch{throw new Error('Multiplayer needs the online game server. Use the multiplayer site link.');}if(!res.ok)throw new Error(data.error||'Connection failed');return data;}
function lobbyUI(data){$('roomCode').textContent=data.code;$('players').replaceChildren(...data.game.racers.filter(r=>!r.bot).map(r=>{const li=document.createElement('li');li.textContent=r.name+(r.id===data.host?' · host':'');return li;}));$('hostStart').hidden=data.host!==myId;$('lobbyHint').textContent=data.host===myId?'Share this code, wait for friends, then start. Empty spots get AI racers.':'Waiting for the host to start…';}
async function connect(action){if(networkBusy)return;networkBusy=true;$('netStatus').textContent='Connecting…';try{const data=await api(action,{name:$('nickname').value,code:$('joinCode').value.trim().toUpperCase(),track:+$('track').value});session={id:data.id,token:data.token,code:data.code};myId=data.id;g=data.game;t=S.circuit(g.track);makeWorld();camera=null;visuals.clear();mode='online';failures=0;resultShown=false;hidePanels();$('lobby').hidden=false;lobbyUI(data);$('netStatus').textContent='';sync();}catch(e){$('netStatus').textContent=e.message;}finally{networkBusy=false;}}
async function sync(){if(!session)return;const active=session;try{const sent=input();queuedItem=false;const data=await api('sync',{input:sent});if(session!==active)return;g=data.game;failures=0;$('connection').textContent='ONLINE · '+session.code;if(g.phase==='lobby')lobbyUI(data);else $('lobby').hidden=true;}catch(e){if(session!==active)return;failures++;$('connection').textContent='CONNECTION LOST · retrying';if(failures>=4){returnMenu();$('netStatus').textContent='Disconnected: '+e.message;return;}}if(session===active)pollTimer=setTimeout(sync,g.phase==='lobby'?450:65);}
async function hostStart(){try{const data=await api('start');g=data.game;$('lobby').hidden=true;keys.clear();$('hostStart').blur();}catch(e){$('lobbyHint').textContent=e.message;}}
function pause(){if(mode==='menu')return;if(mode==='online'){$('toast').textContent='Online races keep running. Hold brake to stop.';return;}paused=!paused;$('paused').hidden=!paused;keys.clear();}
function result(){resultShown=true;const p=me(),order=S.order(g),place=order.indexOf(p)+1;$('resultTitle').textContent=p.finish===null?'Race ended':place===1?'You take the gold!':'Finished '+place+(['st','nd','rd'][place-1]||'th')+'!';$('resultTime').textContent=t.name+' · '+format(p.finish??g.elapsed)+' · penalties +'+p.penalty+'s'+(g.phase!=='finished'?' · provisional until all racers finish':'');if(mode==='solo'&&p.finish!==null){try{const k='turbo-trails-3d-best-'+g.track+'-'+g.difficulty,old=+localStorage.getItem(k);if(!old||p.finish<old)localStorage.setItem(k,p.finish);}catch{}};$('standings').replaceChildren(...order.map(r=>{const li=document.createElement('li');li.textContent=r.name+' — '+(r.finish===null?'racing…':format(r.finish))+' (+'+r.penalty+'s)';return li;}));$('results').hidden=false;$('again').hidden=mode==='online';keys.clear();}
function hud(){const p=me();if(!p)return;$('position').textContent=(S.order(g).findIndex(r=>r.id===myId)+1)+' / '+g.racers.length;$('lap').textContent=clamp(Math.floor(p.total/t.length)+1,1,3)+' / 3';$('time').textContent=format(g.elapsed+p.penalty);$('speed').textContent=Math.round(p.speed*.7);$('item').textContent=p.item||'—';$('drift').style.width=(p.drift/1.3*100)+'%';$('penalty').textContent='PENALTIES +'+p.penalty+'s';if(mode==='menu')return;let msg='';if(g.phase==='countdown')msg=String(Math.max(1,Math.ceil(g.countdown)));else if(p.resetNotice>0)msg='TRACK RESET · +3 SECONDS';else if(p.offTime>0)msg='OFF TRACK · SLOWDOWN · RETURN NOW';else if(p.drift>=1)msg='RELEASE DRIFT FOR BOOST';else if(p.boost>0)msg='TURBO BOOST';else if(p.shield>0)msg='SHIELD ACTIVE';$('toast').textContent=msg;if(p.finish!==null||g.phase==='finished')result();}
// Perspective 3D renderer: world-space polygons, near-plane clipping, depth sorting.
function poly(points,color){return{points,color};}
function box(x,z,y,w,d,h,color,angle=0){const c=Math.cos(angle),s=Math.sin(angle),v=(a,b,k)=>({x:x+a*c-b*s,z:z+a*s+b*c,y:y+k}),p=[v(-w/2,-d/2,0),v(w/2,-d/2,0),v(w/2,d/2,0),v(-w/2,d/2,0)],q=[v(-w/2,-d/2,h),v(w/2,-d/2,h),v(w/2,d/2,h),v(-w/2,d/2,h)];return[poly(q,color),...p.map((a,i)=>poly([a,p[(i+1)%4],q[(i+1)%4],q[i]],i%2?shade(color,.7):shade(color,.85)))];}
function shade(hex,f){return '#'+[1,3,5].map(i=>Math.round(parseInt(hex.slice(i,i+2),16)*f).toString(16).padStart(2,'0')).join('');}
function point(s,lane,y=0){const p=S.sample(t,s,lane);return{x:p.x,z:p.y,y};}
function makeWorld(){world=[];for(let i=0;i<t.path.length;i++){const a=t.path[i],end=a.s+a.len;world.push(poly([point(a.s,-59),point(end,-59),point(end,59),point(a.s,59)],i%2?'#ee8d88':t.edge));world.push(poly([point(a.s,-47,.35),point(end,-47,.35),point(end,47,.35),point(a.s,47,.35)],t.road));if(i%4<2)world.push(poly([point(a.s,-1,.5),point(end,-1,.5),point(end,1,.5),point(a.s,1,.5)],'#b5c0cb'));}
for(let i=0;i<12;i++)for(let j=0;j<2;j++)world.push(poly([point(j*6,i*8-48,.7),point(j*6+6,i*8-48,.7),point(j*6+6,i*8-40,.7),point(j*6,i*8-40,.7)],(i+j)%2?'#ffffff':'#152334'));
for(const f of [.25,.68]){const s=t.length*f;world.push(poly([point(s-17,-32,1),point(s+17,-32,1),point(s+17,32,1),point(s-17,32,1)],'#b9ff66'));for(let k=0;k<3;k++)world.push(poly([point(s-12+k*10,-18,1.1),point(s-4+k*10,0,1.1),point(s-12+k*10,18,1.1)],'#257b71'));}
for(let i=0;i<100;i++){const x=(i*173+47)%1280-40,z=(i*137+29)%860-40;if(S.nearest(t,x,z).distance<85)continue;world.push(...box(x,z,0,7,7,28,'#87664e'));for(let j=0;j<5;j++){const a=j*Math.PI*2/5,b=(j+1)*Math.PI*2/5;world.push(poly([{x:x+Math.cos(a)*23,z:z+Math.sin(a)*23,y:20},{x:x+Math.cos(b)*23,z:z+Math.sin(b)*23,y:20},{x,z,y:65+i%15}],g.track===1?'#c9a267':g.track===2?'#527a87':j%2?'#50bd87':'#388b6a'));}}
}
function kart(r){const list=box(r.x,r.y,3,28,17,8,r.color,r.angle);list.push(...box(r.x-3*Math.cos(r.angle),r.y-3*Math.sin(r.angle),11,12,12,9,'#26374b',r.angle),...box(r.x,r.y,20,8,8,7,'#fff0d1',r.angle));for(const a of [-9,9])for(const b of [-11,11])list.push(...box(r.x+a*Math.cos(r.angle)-b*Math.sin(r.angle),r.y+a*Math.sin(r.angle)+b*Math.cos(r.angle),1,9,5,10,'#192332',r.angle));if(r.boost>0)list.push(...box(r.x-23*Math.cos(r.angle),r.y-23*Math.sin(r.angle),5,15+Math.random()*10,10,5,'#ffc55b',r.angle));if(r.shield>0){for(let i=0;i<10;i++){const a=i*Math.PI/5,b=(i+1)*Math.PI/5;list.push(poly([{x:r.x+Math.cos(a)*25,z:r.y+Math.sin(a)*25,y:2},{x:r.x+Math.cos(b)*25,z:r.y+Math.sin(b)*25,y:2},{x:r.x+Math.cos(b)*25,z:r.y+Math.sin(b)*25,y:4},{x:r.x+Math.cos(a)*25,z:r.y+Math.sin(a)*25,y:4}],'#7defff'));}}return list;}
function draw(dt){let p=me();if(!p)return;const alpha=1-Math.exp(-dt*18);for(const r of g.racers){let v=visuals.get(r.id);if(!v||Math.hypot(v.x-r.x,v.y-r.y)>120){v={...r};visuals.set(r.id,v);}else{v.x+=(r.x-v.x)*alpha;v.y+=(r.y-v.y)*alpha;v.angle+=angleDiff(r.angle,v.angle)*alpha;for(const k of ['boost','shield','color','name','drift'])v[k]=r[k];}}p=visuals.get(p.id)||p;
const target={x:p.x-Math.cos(p.angle)*100,z:p.y-Math.sin(p.angle)*100,y:64,angle:p.angle};if(!camera)camera=target;else{const f=1-Math.exp(-dt*7);camera.x+=(target.x-camera.x)*f;camera.z+=(target.z-camera.z)*f;camera.angle+=angleDiff(target.angle,camera.angle)*f;}
const ca=Math.cos(camera.angle),sa=Math.sin(camera.angle),pitch=.29,cp=Math.cos(pitch),sp=Math.sin(pitch),focal=680;
function view(v){const dx=v.x-camera.x,dz=v.z-camera.z,forward=dx*ca+dz*sa,h=v.y-camera.y;return{x:-dx*sa+dz*ca,y:h*cp+forward*sp,z:forward*cp-h*sp};}
function project(v){return{x:W/2+v.x*focal/v.z,y:H*.43-v.y*focal/v.z};}
const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,t.sky);sky.addColorStop(.55,g.track===2?'#47627b':'#f2edcf');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle=t.ground;ctx.fillRect(0,H*.43-Math.tan(pitch)*focal,W,H);
ctx.fillStyle=g.track===2?'#718799':'#a4bbc0';ctx.beginPath();ctx.moveTo(0,170);for(let i=0;i<13;i++)ctx.lineTo(i*110,95+Math.sin(i*1.4)*45);ctx.lineTo(W,190);ctx.lineTo(0,190);ctx.fill();
let scene=world.slice();for(const r of g.racers)scene.push(...kart(visuals.get(r.id)||r));for(let i=0;i<4;i++)if(!g.boxes[i]){const b=S.sample(t,t.length*[.15,.36,.58,.8][i]);scene.push(...box(b.x,b.y,10+Math.sin(performance.now()/400)*3,18,18,18,'#c6a0ff',performance.now()/1000));}
const faces=[];for(const face of scene){let vertices=face.points.map(view);if(vertices.every(v=>v.z<5)||vertices.every(v=>v.z>1500))continue;let clipped=[];for(let i=0;i<vertices.length;i++){const a=vertices[i],b=vertices[(i+1)%vertices.length];if(a.z>=5)clipped.push(a);if((a.z>=5)!==(b.z>=5)){const f=(5-a.z)/(b.z-a.z);clipped.push({x:a.x+(b.x-a.x)*f,y:a.y+(b.y-a.y)*f,z:5});}}if(clipped.length<3)continue;const points=clipped.map(project);if(points.every(p=>p.x<0)||points.every(p=>p.x>W)||points.every(p=>p.y<0)||points.every(p=>p.y>H))continue;faces.push({points,color:face.color,depth:vertices.reduce((a,v)=>a+v.z,0)/vertices.length});}faces.sort((a,b)=>b.depth-a.depth);for(const f of faces){ctx.fillStyle=f.color;ctx.beginPath();f.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fill();}
// Mini-map remains readable while the chase camera follows the kart.
ctx.fillStyle='#132239dd';ctx.fillRect(20,H-155,190,135);ctx.strokeStyle='#8096ac';ctx.lineWidth=5;ctx.beginPath();t.path.forEach((p,i)=>{const x=30+p.x*.14,y=H-145+p.y*.14;i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.closePath();ctx.stroke();for(const r of g.racers){ctx.fillStyle=r.id===myId?'#b9ff66':r.color;ctx.beginPath();ctx.arc(30+r.x*.14,H-145+r.y*.14,r.id===myId?5:3,0,Math.PI*2);ctx.fill();}
}
function frame(now){const dt=Math.min((now-last)/1000||.016,.04);last=now;if(mode==='solo'&&!paused){const p=me();p.input=input();queuedItem=false;S.step(g,t,dt);}draw(dt);hud();requestAnimationFrame(frame);}
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','BUTTON'].includes(document.activeElement.tagName))return;const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();keys.add(k);if(!e.repeat){if(k===' ')queuedItem=true;if(k==='p'||k==='escape')pause();}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();if(mode==='solo'&&!paused)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();if(mode==='solo'&&!paused)pause();}});
for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);});for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>keys.delete(b.dataset.key));}
$('start').onclick=solo;$('again').onclick=()=>{solo();$('again').blur();};$('pause').onclick=()=>{pause();$('pause').blur();};$('resume').onclick=()=>{pause();$('resume').blur();};$('quit').onclick=returnMenu;$('change').onclick=returnMenu;$('leave').onclick=returnMenu;$('track').onchange=preview;$('color').onchange=preview;$('touchItem').onclick=()=>{queuedItem=true;$('touchItem').blur();};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(sound));beep();$('sound').blur();};$('createRoom').onclick=()=>connect('create');$('joinRoom').onclick=()=>connect('join');$('hostStart').onclick=hostStart;
$('copyCode').onclick=async()=>{try{await navigator.clipboard.writeText(session.code);$('lobbyHint').textContent='Room code copied!';}catch{$('lobbyHint').textContent='Share the room code shown above.';}};
preview();requestAnimationFrame(frame);
