'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),S=require('./sim.js'),{createServer}=require('./server.cjs');
function race(track=0){const t=S.circuit(track),g=S.create(track,1);g.racers=[S.racer(t,'you','You',0)];S.start(g,t);g.phase='race';return{g,t,r:g.racers[0]};}
test('AI completes every 3D circuit with enforced track limits',()=>{for(let track=0;track<3;track++){const{g,t,r}=race(track);r.bot=true;for(let i=0;i<18000&&g.phase!=='finished';i++)S.step(g,t,1/60);assert.notEqual(r.finish,null,'track '+track);assert.equal(r.penalty,0,'AI should stay on circuit '+track);}});
test('grass cancels boost and sharply reduces speed',()=>{const{g,t,r}=race();Object.assign(r,S.sample(t,0,65));r.s=0;r.speed=240;r.boost=2;r.input={gas:true};for(let i=0;i<25;i++)S.step(g,t,1/60);assert.equal(r.boost,0);assert.ok(r.speed<=70);});
test('far-off-track reset returns to checkpoint and adds three seconds',()=>{const{g,t,r}=race();const before=r.safe;Object.assign(r,S.sample(t,600,200));r.total=999;r.speed=200;S.step(g,t,1/60);assert.equal(r.total,before);assert.equal(r.penalty,3);assert.equal(r.speed,0);assert.ok(S.nearest(t,r.x,r.y).distance<1);});
test('lingering off-road also resets; penalties affect finish ordering',()=>{const{g,t,r}=race();Object.assign(r,S.sample(t,0,65));for(let i=0;i<160;i++)S.step(g,t,1/60);assert.equal(r.penalty,3);g.racers.push({...r,id:'other',finish:50});r.finish=53;assert.equal(S.order(g)[0].id,'other');});
test('drift, braking and shield-protected pulse work',()=>{const{g,t,r}=race();r.speed=180;r.drift=1.2;S.step(g,t,1/60);assert.ok(r.boost>0);r.item='Shield';S.use(g,r);assert.equal(r.shield,6);const b=S.racer(t,'b','B',1);b.total=r.total+100;b.shield=2;g.racers.push(b);r.item='Pulse';S.use(g,r);assert.equal(b.stun,0);b.shield=0;r.item='Pulse';S.use(g,r);assert.equal(b.stun,2);r.input={brake:true};for(let i=0;i<60;i++)S.step(g,t,1/60);assert.equal(r.speed,0);});
test('real HTTP room lifecycle, authentication, capacity and shared movement',async()=>{const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const post=async b=>{const res=await fetch(base+'/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});return{status:res.status,data:await res.json()};};try{
const a=(await post({action:'create',name:'Host',track:1})).data,b=(await post({action:'join',name:'Friend',code:a.code})).data;assert.equal(a.code,b.code);const auth=d=>({code:d.code,id:d.id,token:d.token});assert.equal((await post({...auth(b),action:'start'})).status,403);assert.equal((await post({...auth(a),token:'wrong',action:'sync'})).status,403);for(let i=0;i<4;i++)assert.equal((await post({action:'join',code:a.code,name:'Guest'+i})).status,200);assert.equal((await post({action:'join',code:a.code})).status,409);
const started=(await post({...auth(a),action:'start'})).data;assert.equal(started.game.racers.length,6);assert.equal(started.game.phase,'countdown');assert.equal((await post({action:'join',code:a.code})).status,409);assert.equal(JSON.stringify(started.game).includes(a.token),false);
await new Promise(r=>setTimeout(r,3200));await post({...auth(a),action:'sync',input:{gas:true,steer:0}});await new Promise(r=>setTimeout(r,350));const snap=(await post({...auth(b),action:'sync',input:{}})).data;assert.ok(snap.game.racers.find(r=>r.id===a.id).speed>20);assert.equal(snap.game.racers.find(r=>r.id===b.id).speed,0);await post({...auth(a),action:'leave'});const after=(await post({...auth(b),action:'sync'})).data;assert.equal(after.host,b.id);assert.equal(after.game.racers.find(r=>r.id===a.id).bot,true);
assert.equal((await fetch(base+'/sim.js')).status,200);assert.equal((await fetch(base+'/server.cjs')).status,404);
}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}});
